#pragma once

#include "ActionManager.h"

#include <SDL3/SDL_events.h>
#include <array>

static constexpr size_t MaxActionCount = 32;

class Action
{
public:
    explicit Action(FrameNumber frame = 0) : Frame(frame), m_ActionMapper(nullptr) { }

    void Initialize(ActionManager* actionManager)
    {
        m_ActionMapper = actionManager;
    }

    void Callback(SDL_Event* event)
    {
        if (!m_ActionMapper) return;

        switch (event->type)
        {
            case SDL_EVENT_KEY_DOWN:
            case SDL_EVENT_KEY_UP:
                CallbackKeyboard(event->key);
                break;

            case SDL_EVENT_MOUSE_BUTTON_DOWN:
                case SDL_EVENT_MOUSE_BUTTON_UP:
                CallbackMouseButton(event->button);
                break;

            case SDL_EVENT_MOUSE_MOTION:
                m_MousePosition = Vector2(Fixed16_16::FromFloat(event->motion.x), Fixed16_16::FromFloat(event->motion.y));
                break;

            default:
                break;
        }
    }

    void Update()
    {
        m_LastInput = m_CurrentInput;
    }

    [[nodiscard]] inline bool GetAction(ActionKey actionKey) const
    {
        return m_CurrentInput[actionKey];
    }

    [[nodiscard]] inline bool GetActionDown(ActionKey actionKey) const
    {
        return m_CurrentInput[actionKey] && !m_LastInput[actionKey];
    }

    [[nodiscard]] inline bool GetActionUp(ActionKey actionKey) const
    {
        return !m_CurrentInput[actionKey] && m_LastInput[actionKey];
    }

    [[nodiscard]] bool GetKey(SDL_Scancode scanCode) const
    {
        if (!m_ActionMapper) return false;

        ActionKey actionKey;
        if (m_ActionMapper->TryGetKeyAction(scanCode, actionKey))
        {
            return m_CurrentInput[actionKey];
        }

        return false;
    }

    [[nodiscard]] inline bool GetKeyDown(SDL_Scancode scanCode) const
    {
        if (!m_ActionMapper) return false;

        ActionKey actionKey;
        if (m_ActionMapper->TryGetKeyAction(scanCode, actionKey))
        {
            return m_CurrentInput[actionKey] && !m_LastInput[actionKey];
        }

        return false;
    }

    [[nodiscard]] inline bool GetKeyUp(SDL_Scancode scanCode) const
    {
        if (!m_ActionMapper) return false;

        ActionKey actionKey;
        if (m_ActionMapper->TryGetKeyAction(scanCode, actionKey))
        {
            return !m_CurrentInput[actionKey] && m_LastInput[actionKey];
        }

        return false;
    }

    [[nodiscard]] bool GetMouseButton(uint8_t mouseButton) const
    {
        if (!m_ActionMapper) return false;

        ActionKey actionKey;
        if (m_ActionMapper->TryGetMouseAction(mouseButton, actionKey))
        {
            return m_CurrentInput[actionKey];
        }

        return false;
    }

    [[nodiscard]] inline bool GetMouseButtonDown(uint8_t mouseButton) const
    {
        if (!m_ActionMapper) return false;

        ActionKey actionKey;
        if (m_ActionMapper->TryGetMouseAction(mouseButton, actionKey))
        {
            return m_CurrentInput[actionKey] && !m_LastInput[actionKey];
        }

        return false;
    }

    [[nodiscard]] inline bool GetMouseButtonUp(uint8_t mouseButton) const
    {
        if (!m_ActionMapper) return false;

        ActionKey actionKey;
        if (m_ActionMapper->TryGetMouseAction(mouseButton, actionKey))
        {
            return !m_CurrentInput[actionKey] && m_LastInput[actionKey];
        }

        return false;
    }

    [[nodiscard]] inline Vector2 GetMousePosition() const
    {
        return m_MousePosition;
    }

    void Serialize(Stream& stream) const
    {
        stream.WriteBitset<MaxActionCount>(m_CurrentInput);
        stream.WriteBitset<MaxActionCount>(m_LastInput);
    }

    void Deserialize(Stream&& stream)
    {
        m_CurrentInput = stream.ReadBitset<MaxActionCount>();
        m_LastInput = stream.ReadBitset<MaxActionCount>();
    }

private:
    void CallbackKeyboard(const SDL_KeyboardEvent& event)
    {
        //Filter out input events which are generated by holding down keys
        if (event.repeat || event.scancode >= SDL_SCANCODE_COUNT) return;

        ActionKey actionKey;
        if (m_ActionMapper->TryGetKeyAction(event.scancode, actionKey))
        {
            m_CurrentInput[actionKey] = event.down;
        }
    }

    void CallbackMouseButton(const SDL_MouseButtonEvent& event)
    {
        ActionKey actionKey;
        if (m_ActionMapper->TryGetMouseAction(event.button, actionKey))
        {
            m_CurrentInput[actionKey] = event.down;
        }
    }

public:
    FrameNumber Frame;

private:
    std::bitset<MaxActionCount> m_CurrentInput { };
    std::bitset<MaxActionCount> m_LastInput { };

    Vector2 m_MousePosition;

    ActionManager* m_ActionMapper;
};